import SwiftUI
import SwiftThemeKit

// MARK: - Generated ThemeColors

let lightColors1 = ThemeColors(
  primary: .init(hex: "#215fa7"),
  onPrimary: .init(hex: "#ffffff"),
  primaryContainer: .init(hex: "#d5e3ff"),
  onPrimaryContainer: .init(hex: "#004788"),
  secondary: .init(hex: "#555f71"),
  onSecondary: .init(hex: "#ffffff"),
  secondaryContainer: .init(hex: "#d9e3f8"),
  onSecondaryContainer: .init(hex: "#3d4758"),
  tertiary: .init(hex: "#6e5676"),
  onTertiary: .init(hex: "#ffffff"),
  tertiaryContainer: .init(hex: "#f8d8fe"),
  onTertiaryContainer: .init(hex: "#553e5d"),
  background: .init(hex: "#fdfbff"),
  onBackground: .init(hex: "#1a1c1e"),
  error: .init(hex: "#ba1a1a"),
  onError: .init(hex: "#ffffff"),
  errorContainer: .init(hex: "#ffdad6"),
  onErrorContainer: .init(hex: "#93000a"),
  inverseSurface: .init(hex: "#2f3033"),
  inverseOnSurface: .init(hex: "#f1f0f4"),
  inversePrimary: .init(hex: "#a7c8ff"),
  surface: .init(hex: "#faf9fd"),
  onSurface: .init(hex: "#1a1c1e"),
  surfaceVariant: .init(hex: "#e0e2ec"),
  onSurfaceVariant: .init(hex: "#43474e"),
  surfaceDim: .init(hex: "#dad9dd"),
  surfaceBright: .init(hex: "#faf9fd"),
  surfaceContainerLowest: .init(hex: "#ffffff"),
  surfaceContainerLow: .init(hex: "#f4f3f7"),
  surfaceContainer: .init(hex: "#eeedf1"),
  surfaceContainerHigh: .init(hex: "#e9e7eb"),
  surfaceContainerHighest: .init(hex: "#e3e2e6"),
  outline: .init(hex: "#74777f"),
  outlineVariant: .init(hex: "#c4c6cf"),
  scrim: .init(hex: "#000000"),
  shadow: .init(hex: "#000000")
)

let darkColors1 = ThemeColors(
  primary: .init(hex: "#a7c8ff"),
  onPrimary: .init(hex: "#003060"),
  primaryContainer: .init(hex: "#004788"),
  onPrimaryContainer: .init(hex: "#d5e3ff"),
  secondary: .init(hex: "#bdc7dc"),
  onSecondary: .init(hex: "#273141"),
  secondaryContainer: .init(hex: "#3d4758"),
  onSecondaryContainer: .init(hex: "#d9e3f8"),
  tertiary: .init(hex: "#dbbce2"),
  onTertiary: .init(hex: "#3e2845"),
  tertiaryContainer: .init(hex: "#553e5d"),
  onTertiaryContainer: .init(hex: "#f8d8fe"),
  background: .init(hex: "#1a1c1e"),
  onBackground: .init(hex: "#e3e2e6"),
  error: .init(hex: "#ffb4ab"),
  onError: .init(hex: "#690005"),
  errorContainer: .init(hex: "#93000a"),
  onErrorContainer: .init(hex: "#ffdad6"),
  inverseSurface: .init(hex: "#e3e2e6"),
  inverseOnSurface: .init(hex: "#2f3033"),
  inversePrimary: .init(hex: "#215fa7"),
  surface: .init(hex: "#121316"),
  onSurface: .init(hex: "#e3e2e6"),
  surfaceVariant: .init(hex: "#43474e"),
  onSurfaceVariant: .init(hex: "#c4c6cf"),
  surfaceDim: .init(hex: "#121316"),
  surfaceBright: .init(hex: "#38393c"),
  surfaceContainerLowest: .init(hex: "#0d0e11"),
  surfaceContainerLow: .init(hex: "#1a1c1e"),
  surfaceContainer: .init(hex: "#1e2023"),
  surfaceContainerHigh: .init(hex: "#292a2d"),
  surfaceContainerHighest: .init(hex: "#343538"),
  outline: .init(hex: "#8e9199"),
  outlineVariant: .init(hex: "#43474e"),
  scrim: .init(hex: "#000000"),
  shadow: .init(hex: "#000000")
)

let lightColors2 = ThemeColors(
  primary: .init(hex: "#1c6d21"),
  onPrimary: .init(hex: "#ffffff"),
  primaryContainer: .init(hex: "#a3f699"),
  onPrimaryContainer: .init(hex: "#00530e"),
  secondary: .init(hex: "#53634e"),
  onSecondary: .init(hex: "#ffffff"),
  secondaryContainer: .init(hex: "#d6e8ce"),
  onSecondaryContainer: .init(hex: "#3b4b38"),
  tertiary: .init(hex: "#38656a"),
  onTertiary: .init(hex: "#ffffff"),
  tertiaryContainer: .init(hex: "#bcebf0"),
  onTertiaryContainer: .init(hex: "#1e4d52"),
  background: .init(hex: "#fcfdf6"),
  onBackground: .init(hex: "#1a1c19"),
  error: .init(hex: "#ba1a1a"),
  onError: .init(hex: "#ffffff"),
  errorContainer: .init(hex: "#ffdad6"),
  onErrorContainer: .init(hex: "#93000a"),
  inverseSurface: .init(hex: "#2f312d"),
  inverseOnSurface: .init(hex: "#f1f1eb"),
  inversePrimary: .init(hex: "#88da80"),
  surface: .init(hex: "#f9faf3"),
  onSurface: .init(hex: "#1a1c19"),
  surfaceVariant: .init(hex: "#dee5d8"),
  onSurfaceVariant: .init(hex: "#42493f"),
  surfaceDim: .init(hex: "#dadad4"),
  surfaceBright: .init(hex: "#f9faf3"),
  surfaceContainerLowest: .init(hex: "#ffffff"),
  surfaceContainerLow: .init(hex: "#f3f4ee"),
  surfaceContainer: .init(hex: "#eeeee8"),
  surfaceContainerHigh: .init(hex: "#e8e9e2"),
  surfaceContainerHighest: .init(hex: "#e2e3dd"),
  outline: .init(hex: "#73796f"),
  outlineVariant: .init(hex: "#c2c8bd"),
  scrim: .init(hex: "#000000"),
  shadow: .init(hex: "#000000")
)

let darkColors2 = ThemeColors(
  primary: .init(hex: "#88da80"),
  onPrimary: .init(hex: "#003907"),
  primaryContainer: .init(hex: "#00530e"),
  onPrimaryContainer: .init(hex: "#a3f699"),
  secondary: .init(hex: "#baccb3"),
  onSecondary: .init(hex: "#253423"),
  secondaryContainer: .init(hex: "#3b4b38"),
  onSecondaryContainer: .init(hex: "#d6e8ce"),
  tertiary: .init(hex: "#a0cfd3"),
  onTertiary: .init(hex: "#00363b"),
  tertiaryContainer: .init(hex: "#1e4d52"),
  onTertiaryContainer: .init(hex: "#bcebf0"),
  background: .init(hex: "#1a1c19"),
  onBackground: .init(hex: "#e2e3dd"),
  error: .init(hex: "#ffb4ab"),
  onError: .init(hex: "#690005"),
  errorContainer: .init(hex: "#93000a"),
  onErrorContainer: .init(hex: "#ffdad6"),
  inverseSurface: .init(hex: "#e2e3dd"),
  inverseOnSurface: .init(hex: "#2f312d"),
  inversePrimary: .init(hex: "#1c6d21"),
  surface: .init(hex: "#121411"),
  onSurface: .init(hex: "#e2e3dd"),
  surfaceVariant: .init(hex: "#42493f"),
  onSurfaceVariant: .init(hex: "#c2c8bd"),
  surfaceDim: .init(hex: "#121411"),
  surfaceBright: .init(hex: "#383a36"),
  surfaceContainerLowest: .init(hex: "#0c0f0c"),
  surfaceContainerLow: .init(hex: "#1a1c19"),
  surfaceContainer: .init(hex: "#1e201d"),
  surfaceContainerHigh: .init(hex: "#282b27"),
  surfaceContainerHighest: .init(hex: "#333531"),
  outline: .init(hex: "#8c9388"),
  outlineVariant: .init(hex: "#42493f"),
  scrim: .init(hex: "#000000"),
  shadow: .init(hex: "#000000")
)

let lightColors3 = ThemeColors(
  primary: .init(hex: "#a9371b"),
  onPrimary: .init(hex: "#ffffff"),
  primaryContainer: .init(hex: "#ffdad2"),
  onPrimaryContainer: .init(hex: "#882005"),
  secondary: .init(hex: "#77574f"),
  onSecondary: .init(hex: "#ffffff"),
  secondaryContainer: .init(hex: "#ffdad2"),
  onSecondaryContainer: .init(hex: "#5d4038"),
  tertiary: .init(hex: "#6d5d2e"),
  onTertiary: .init(hex: "#ffffff"),
  tertiaryContainer: .init(hex: "#f7e1a6"),
  onTertiaryContainer: .init(hex: "#544519"),
  background: .init(hex: "#fffbff"),
  onBackground: .init(hex: "#201a19"),
  error: .init(hex: "#ba1a1a"),
  onError: .init(hex: "#ffffff"),
  errorContainer: .init(hex: "#ffdad6"),
  onErrorContainer: .init(hex: "#93000a"),
  inverseSurface: .init(hex: "#362f2d"),
  inverseOnSurface: .init(hex: "#fbeeeb"),
  inversePrimary: .init(hex: "#ffb4a2"),
  surface: .init(hex: "#fff8f6"),
  onSurface: .init(hex: "#201a19"),
  surfaceVariant: .init(hex: "#f5ddd8"),
  onSurfaceVariant: .init(hex: "#534340"),
  surfaceDim: .init(hex: "#e4d7d4"),
  surfaceBright: .init(hex: "#fff8f6"),
  surfaceContainerLowest: .init(hex: "#ffffff"),
  surfaceContainerLow: .init(hex: "#fef1ee"),
  surfaceContainer: .init(hex: "#f8ebe8"),
  surfaceContainerHigh: .init(hex: "#f3e5e2"),
  surfaceContainerHighest: .init(hex: "#ede0dd"),
  outline: .init(hex: "#85736f"),
  outlineVariant: .init(hex: "#d8c2bd"),
  scrim: .init(hex: "#000000"),
  shadow: .init(hex: "#000000")
)

let darkColors3 = ThemeColors(
  primary: .init(hex: "#ffb4a2"),
  onPrimary: .init(hex: "#621100"),
  primaryContainer: .init(hex: "#882005"),
  onPrimaryContainer: .init(hex: "#ffdad2"),
  secondary: .init(hex: "#e7bdb3"),
  onSecondary: .init(hex: "#442a23"),
  secondaryContainer: .init(hex: "#5d4038"),
  onSecondaryContainer: .init(hex: "#ffdad2"),
  tertiary: .init(hex: "#dac58c"),
  onTertiary: .init(hex: "#3c2f04"),
  tertiaryContainer: .init(hex: "#544519"),
  onTertiaryContainer: .init(hex: "#f7e1a6"),
  background: .init(hex: "#201a19"),
  onBackground: .init(hex: "#ede0dd"),
  error: .init(hex: "#ffb4ab"),
  onError: .init(hex: "#690005"),
  errorContainer: .init(hex: "#93000a"),
  onErrorContainer: .init(hex: "#ffdad6"),
  inverseSurface: .init(hex: "#ede0dd"),
  inverseOnSurface: .init(hex: "#362f2d"),
  inversePrimary: .init(hex: "#a9371b"),
  surface: .init(hex: "#181211"),
  onSurface: .init(hex: "#ede0dd"),
  surfaceVariant: .init(hex: "#534340"),
  onSurfaceVariant: .init(hex: "#d8c2bd"),
  surfaceDim: .init(hex: "#181211"),
  surfaceBright: .init(hex: "#3f3736"),
  surfaceContainerLowest: .init(hex: "#120d0c"),
  surfaceContainerLow: .init(hex: "#201a19"),
  surfaceContainer: .init(hex: "#251e1d"),
  surfaceContainerHigh: .init(hex: "#2f2827"),
  surfaceContainerHighest: .init(hex: "#3b3331"),
  outline: .init(hex: "#a08c88"),
  outlineVariant: .init(hex: "#534340"),
  scrim: .init(hex: "#000000"),
  shadow: .init(hex: "#000000")
)

// MARK: - Generated Theme

let lightTheme1: Theme = .defaultLight.copy(colors: lightColors1)

let darkTheme1: Theme = .defaultDark.copy(colors: darkColors1.copy(primary: .blue))

let lightTheme2: Theme = .defaultLight.copy(colors: lightColors2,
                                            buttons: .defaultLight.copy(shape: .capsule))

let darkTheme2: Theme = .defaultDark.copy(colors: darkColors2,
                                          buttons: .defaultDark.copy(shape: .capsule))

let lightTheme3: Theme = .defaultLight.copy(colors: lightColors3,
                                            buttons: .defaultLight.copy(shape: .square))

let darkTheme3: Theme = .defaultDark.copy(colors: darkColors3,
                                          buttons: .defaultDark.copy(shape: .square))
